---
apiVersion: v1
kind: Secret
metadata:
  name: wallet-secrets
  namespace: wallet
type: Opaque
data:
  username: cm9vdA==
  password: TXlTcWwyMDE5IQ==


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet
  namespace: wallet
  labels:
    app: "wallet"
    project: "capstone"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "wallet"
      project: "capstone"
  template:
    metadata:
      labels:
        app: "wallet"
        project: "capstone"
    spec:
      containers:
      - name: wallet
        image: brunoguidone/wallet:latest
        envFrom:
            - secretRef:
               name: wallet-secrets
        ports:
            - containerPort: 5000
        resources:
          requests:
            memory: "100Mi"
            cpu: "150m"
          limits:
            memory: "200Mi"
            cpu: "200m"



---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  namespace: wallet
  name: wallet-hpa
  labels:
    app: "wallet"
    project: "capstone"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wallet
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60


---
apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  namespace: wallet
  labels:
    app: "wallet"
    project: "capstone"
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: "wallet"
    project: "capstone"
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wallet-ingress
  namespace: wallet
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/load-balance: ewma
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
spec:
  rules:
  - host: wallet.guidone.com.br
    http:
      paths:
      - path: /
        backend:
          serviceName: wallet-service
          servicePort: 80